name: py2
channels:
  - defaults
dependencies:
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py27_0
  - libcxx=4.0.1=hcfea43d_1
  - libcxxabi=4.0.1=hcfea43d_1
  - libedit=3.1.20181209=hb402a30_0
  - libffi=3.2.1=h475c297_4
  - ncurses=6.1=h0a44026_1
  - pip=19.3.1=py27_0
  - python=2.7.17=h97142e2_0
  - readline=7.0=h1de35cc_5
  - setuptools=42.0.2=py27_0
  - sqlite=3.30.1=ha441bb4_0
  - tk=8.6.8=ha441bb4_0
  - wheel=0.33.6=py27_0
  - zlib=1.2.11=h1de35cc_3
  - pip:
    - backports-functools-lru-cache==1.6.1
    - beautifulsoup4==4.8.1
    - bs4==0.0.1
    - chardet==3.0.4
    - idna==2.8
    - lxml==4.4.2
    - requests==2.22.0
    - soupsieve==1.9.5
    - urllib3==1.25.7
